export const products = [
  {
    id: 1,
    productNo: 101,
    name: "Amul Butter 100gm",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 2,
    productNo: 102,
    name: "Amul Processed Cheese 100gm",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 3,
    productNo: 103,
    name: "Amul Chiplet",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 4,
    productNo: 104,
    name: "Amul Fresh Cream 100gm",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 5,
    productNo: 105,
    name: "Amul Milk Rusk 100gm",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 6,
    productNo: 106,
    name: "Amul Shrikhand 100gm",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 7,
    productNo: 107,
    name: "Amul Dice Cheese 100gm",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 8,
    productNo: 108,
    name: "Amul Dark Chocolate",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 9,
    productNo: 109,
    name: "Delicious Butter",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 10,
    productNo: 110,
    name: "Amul Spray",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 11,
    productNo: 111,
    name: "Amul Chocomini",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 12,
    productNo: 112,
    name: "Amul Cheese Spread",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 13,
    productNo: 113,
    name: "Amul Masti Buttermilk",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 14,
    productNo: 114,
    name: "Amul Lassi",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
  {
    id: 15,
    productNo: 115,
    name: "Amul Kool Kesar",
    price: 55,
    timesInvoiced: 13,
    totalInvoiced: 2315,
  },
];
